# Generated by Django 3.1.7 on 2021-03-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(unique=True)),
                ('question', models.CharField(default='Ask Anything', max_length=5000)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False, verbose_name='answer_status')),
                ('answer', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
