# Generated by Django 3.1.7 on 2021-03-13 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityQnA', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qna',
            options={'verbose_name': 'QnA', 'verbose_name_plural': 'QnAs'},
        ),
    ]
