# Generated by Django 3.1.7 on 2021-03-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunityQnA', '0003_auto_20210313_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qna',
            options={'verbose_name': 'QnA', 'verbose_name_plural': 'QnA'},
        ),
        migrations.AlterField(
            model_name='qna',
            name='answer',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
